### PR TITLE
Create Bmesh Lite Node

### PR DESCRIPTION
**Pull request by FredRus**
Add bmesh_ops_lite.py to nodes

### CODE REVIEW

**Comment by vkter** [comment]
If you want to display the node in the menu, you also need to add node class names to Sverchok-Bmesh/__init__.py

**Comment by vkter** [comment]
image

**Comment by vkter** [comment]
image
The node runs successfully, but there seems to be some problems, but it doesn't matter. You can continue to repair it later. Do you have any changes to the node? If not, I will agree to merge it into the trunk

**Comment by FredRus** [comment]
I think the two problems are:

1.  The 'SAMPLE_INDEX' icon is not part of the original blender but is a fork from BforArtists, so the ui drawing fails.
2. The text naming needs to be changed in the sverchok.core.sockets.SvTextSocket, the draw property text should refer to the name of the socket. This otherwise will just draw 'default_property'

Once these problems are fixed, there comes another problem.
After calculating the indices of newly created geometry, the next operation becomes recursive and sometimes crashes blender. There is a need to re-update the BMesh In Node at some moment. This is too experimental to be merged at the moment,
but once I become more confident, I'll inform you.

**Comment by FredRus** [comment]
I have updated the node and moved it to the main branch. It is somewhat stable now. Test it, with several nodes, and if you are okay with it, you can merge it. The socket properties are an issue with Sverchok so I did not change the source during the making of the node.

**Pull request closed without merging**
