### PR TITLE
Confirm Bmesh Ops Lite

### PR DESCRIPTION
**Pull request by FredRus**
I think the node is now less experimental and can be merged if you like.

### CODE REVIEW

**Comment by vkter** [comment]
The project is happy to merge some experimental things, which represents more possibilities.Before the improvement, 
there are some basic problems that need to be solved:
1. Due to the compatibility of the edit icon, it needs to be deleted
3. In order to facilitate use, can you give some cases

**Comment by FredRus** [comment]
What icon available do you recommend?
I am not sure I understood what you mean by:
> 2. In order to facilitate use, can you give some cases

**Comment by vkter** [comment]
Icon modification：
bl_icon = 'EDITMODE_HLT'
sv_icon = 'SV_BM_BM'
examples：
What kind of data should be entered for some key inputs?
image

**Comment by FredRus** [comment]
The two major differences with the actual Bmesh ops node are:
1. For geometry inputs [edges, faces, vertices] you input a mask or list of integers as indices
2. Only updates the last node

#  Parameters
## Top Enum
Split context for operation
Top enum

## Second Enum
Bmesh operations. Depends on the category you choose on the top Enum.
Second enum

## context
Located in the N-Panel if the input requires Bmesh geometry but the name itself does not state that explicitly.
Only enabled if not in create mode.
context


# Preferences
## calculate indices:
calculates indices of geometry respectively to their type.
options are verts, edges, faces and probably the unknown geometry type.
context

# Example
example (2)

**Comment by vkter** [comment]
OK, this experimental node can be merged. In the future, we will gradually optimize it

**Pull request merged**
